# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 220, 531, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit_logs = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_logs.setMinimumSize(QtCore.QSize(500, 200))
        self.plainTextEdit_logs.setMaximumSize(QtCore.QSize(500, 200))
        self.plainTextEdit_logs.setStyleSheet("border: 1px solid black;")
        self.plainTextEdit_logs.setObjectName("plainTextEdit_logs")
        self.verticalLayout.addWidget(self.plainTextEdit_logs)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 10, 342, 208))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBox_app = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_app.setMinimumSize(QtCore.QSize(340, 30))
        self.comboBox_app.setMaximumSize(QtCore.QSize(340, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_app.setFont(font)
        self.comboBox_app.setObjectName("comboBox_app")
        self.verticalLayout_2.addWidget(self.comboBox_app)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(240, 30))
        self.label_3.setMaximumSize(QtCore.QSize(240, 30))
        self.label_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_script = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_script.setMinimumSize(QtCore.QSize(240, 30))
        self.comboBox_script.setMaximumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_script.setFont(font)
        self.comboBox_script.setObjectName("comboBox_script")
        self.horizontalLayout.addWidget(self.comboBox_script)
        self.pushButton_reload_scripts = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_reload_scripts.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_reload_scripts.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_reload_scripts.setFont(font)
        self.pushButton_reload_scripts.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_reload_scripts.setObjectName("pushButton_reload_scripts")
        self.horizontalLayout.addWidget(self.pushButton_reload_scripts)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_exec_script = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_exec_script.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_exec_script.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_exec_script.setFont(font)
        self.pushButton_exec_script.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_exec_script.setObjectName("pushButton_exec_script")
        self.verticalLayout_2.addWidget(self.pushButton_exec_script)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 242, 117))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setMinimumSize(QtCore.QSize(240, 30))
        self.label_4.setMaximumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.pushButton_launch_adb = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_launch_adb.setFont(font)
        self.pushButton_launch_adb.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_launch_adb.setObjectName("pushButton_launch_adb")
        self.verticalLayout_4.addWidget(self.pushButton_launch_adb)
        self.pushButton_kill_adb_server = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_kill_adb_server.setMinimumSize(QtCore.QSize(240, 33))
        self.pushButton_kill_adb_server.setMaximumSize(QtCore.QSize(240, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_kill_adb_server.setFont(font)
        self.pushButton_kill_adb_server.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_kill_adb_server.setObjectName("pushButton_kill_adb_server")
        self.verticalLayout_4.addWidget(self.pushButton_kill_adb_server)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Logs:"))
        self.label_2.setText(_translate("MainWindow", "Выбор приложения:"))
        self.label_3.setText(_translate("MainWindow", "Выбор скрипта:"))
        self.pushButton_reload_scripts.setText(_translate("MainWindow", "Reload"))
        self.pushButton_exec_script.setText(_translate("MainWindow", "Exec Script"))
        self.label_4.setText(_translate("MainWindow", "Запуск ADB:"))
        self.pushButton_launch_adb.setText(_translate("MainWindow", "Запуск"))
        self.pushButton_kill_adb_server.setText(_translate("MainWindow", "Завершить ADB"))
