# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 581))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 260, 531, 282))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit_logs = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_logs.setMinimumSize(QtCore.QSize(500, 200))
        self.plainTextEdit_logs.setMaximumSize(QtCore.QSize(500, 200))
        self.plainTextEdit_logs.setStyleSheet("border: 1px solid black;")
        self.plainTextEdit_logs.setObjectName("plainTextEdit_logs")
        self.verticalLayout.addWidget(self.plainTextEdit_logs)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(440, 10, 352, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBox_app = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_app.setMinimumSize(QtCore.QSize(340, 30))
        self.comboBox_app.setMaximumSize(QtCore.QSize(340, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_app.setFont(font)
        self.comboBox_app.setObjectName("comboBox_app")
        self.verticalLayout_2.addWidget(self.comboBox_app)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(240, 30))
        self.label_3.setMaximumSize(QtCore.QSize(240, 30))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBox_script = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_script.setMinimumSize(QtCore.QSize(240, 30))
        self.comboBox_script.setMaximumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_script.setFont(font)
        self.comboBox_script.setObjectName("comboBox_script")
        self.verticalLayout_2.addWidget(self.comboBox_script)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_exec_script = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_exec_script.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_exec_script.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_exec_script.setFont(font)
        self.pushButton_exec_script.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_exec_script.setObjectName("pushButton_exec_script")
        self.horizontalLayout.addWidget(self.pushButton_exec_script)
        self.pushButton_exec_script_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_exec_script_2.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_exec_script_2.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_exec_script_2.setFont(font)
        self.pushButton_exec_script_2.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_exec_script_2.setObjectName("pushButton_exec_script_2")
        self.horizontalLayout.addWidget(self.pushButton_exec_script_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 242, 131))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setMinimumSize(QtCore.QSize(240, 30))
        self.label_4.setMaximumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.pushButton_launch_adb = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_launch_adb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_launch_adb.setFont(font)
        self.pushButton_launch_adb.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_launch_adb.setObjectName("pushButton_launch_adb")
        self.verticalLayout_4.addWidget(self.pushButton_launch_adb)
        self.pushButton_kill_adb_server = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_kill_adb_server.setMinimumSize(QtCore.QSize(240, 33))
        self.pushButton_kill_adb_server.setMaximumSize(QtCore.QSize(240, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_kill_adb_server.setFont(font)
        self.pushButton_kill_adb_server.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(132, 132, 132);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(84, 84, 84);\n"
"    \n"
"}")
        self.pushButton_kill_adb_server.setObjectName("pushButton_kill_adb_server")
        self.verticalLayout_4.addWidget(self.pushButton_kill_adb_server)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(409, 10, 371, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_apk_file = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_apk_file.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_apk_file.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_apk_file.setObjectName("lineEdit_apk_file")
        self.horizontalLayout_2.addWidget(self.lineEdit_apk_file)
        self.pushButton_choose_apk = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_choose_apk.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_choose_apk.setObjectName("pushButton_choose_apk")
        self.horizontalLayout_2.addWidget(self.pushButton_choose_apk)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.pushButton_generate_trace_script = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_generate_trace_script.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_generate_trace_script.setObjectName("pushButton_generate_trace_script")
        self.verticalLayout_5.addWidget(self.pushButton_generate_trace_script)
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ip.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.verticalLayout_3.addWidget(self.lineEdit_ip)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.lineEdit_port = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.verticalLayout_3.addWidget(self.lineEdit_port)
        self.pushButton_save_settings = QtWidgets.QPushButton(self.widget)
        self.pushButton_save_settings.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_save_settings.setObjectName("pushButton_save_settings")
        self.verticalLayout_3.addWidget(self.pushButton_save_settings)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Logs:"))
        self.label_2.setText(_translate("MainWindow", "Выбор приложения:"))
        self.label_3.setText(_translate("MainWindow", "Выбор скрипта:"))
        self.pushButton_exec_script.setText(_translate("MainWindow", "Exec Script"))
        self.pushButton_exec_script_2.setText(_translate("MainWindow", "Update"))
        self.label_4.setText(_translate("MainWindow", "Запуск ADB:"))
        self.pushButton_launch_adb.setText(_translate("MainWindow", "Запуск"))
        self.pushButton_kill_adb_server.setText(_translate("MainWindow", "Завершить ADB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Основная панель"))
        self.label_8.setText(_translate("MainWindow", "Скрипт отслеживания функций"))
        self.label_9.setText(_translate("MainWindow", "APK файл:"))
        self.pushButton_choose_apk.setText(_translate("MainWindow", "Выбрать"))
        self.pushButton_generate_trace_script.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_7.setText(_translate("MainWindow", "Настройки устройства (эмулятора)"))
        self.label_5.setText(_translate("MainWindow", "IP адрес:"))
        self.label_6.setText(_translate("MainWindow", "Порт:"))
        self.pushButton_save_settings.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
